services:
  web:
    build: .
    container_name: pixabay_finder
    ports:
      - 3000:3000
    env_file:
      - .docker.env
    restart: unless-stopped
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    command: yarn dev

volumes:
  nodemodules:
