/* eslint-disable no-console */
// @ts-check
'use client';
import { Inter } from 'next/font/google';
import './styles/globalStyles';
import { Provider } from 'react-redux';
import './styles';
import 'normalize.css';
import 'sal.js/dist/sal.css';
import GlobalStyles from 'styles/globalStyles';
import { store } from './redux/app';
import Head from 'next/head';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, Flip, toast } from 'react-toastify';
import { log } from './functions';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { NEXT_PUBLIC_PIXABAY_KEY } = process.env;

  if (process.env.NODE_ENV === 'development') {
    // eslint-disable-next-line quotes
    log("It's looks like we are in a development mode!", 'log');
  }

  if (!NEXT_PUBLIC_PIXABAY_KEY) {
    toast.error('Missing apiKey? Add it and restart the app!');
    log('Missing apiKey? Add it and restart the app!', 'error');
  }

  if (process.env.NODE_ENV === 'production') {
    console.log = () => {};
    console.warn = () => {};
  }

  return (
    <html lang='en'>
      <Head>
        <title>PixaBayFinder</title>
        <meta charSet='utf-8' />
        <meta httpEquiv='X-UA-Compatible' content='IE=7' />
        <meta httpEquiv='X-UA-Compatible' content='ie=edge' />
        <meta httpEquiv='cache-control' content='no-cache' />
        <meta httpEquiv='expires' content='0' />
        <meta httpEquiv='pragma' content='no-cache' />
        <meta name='author' content='Fadi Hanna' />
        <meta name='keywords' content='API, Search, Pixabay, Finder' />
        <meta
          name='description'
          content='Pixabay Finder search photos from Pixabay API.'
        />
        <link
          type='image/png'
          href='images/pixabay-icon-filled.png'
          rel='icon'
          sizes='any'
        />
        <link
          href='images/pixabay-icon-filled.png?v=1'
          rel='apple-touch-icon'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='theme-color' content='#000000' />
        <meta name='description' content='PixaBayFinder' />
      </Head>
      <Provider store={store}>
        <body className={inter.className}>
          <GlobalStyles />
          {children}
          <ToastContainer theme='dark' transition={Flip} />
        </body>
      </Provider>
    </html>
  );
}
