'use client';
/* eslint-disable quotes */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globalStyles';
import { Provider } from 'react-redux';
import './styles';
import 'normalize.css';
import 'sal.js/dist/sal.css';
import GlobalStyles from 'styles/globalStyles';
import { store } from 'redux/app';
import Head from 'next/head';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, Flip, toast } from 'react-toastify';
import { log } from './functions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (process.env.NODE_ENV === 'development') {
    log("It's looks like we are in a development mode!", 'log');
  }

  const { NEXT_PUBLIC_PIXABAY_KEY } = process.env;

  if (!NEXT_PUBLIC_PIXABAY_KEY) {
    toast.error('Missing apiKey? Add it and restart the app!');
    log('Missing apiKey? Add it and restart the app!', 'error');
  }

  return (
    <html lang='en'>
      <Provider store={store}>
        <Head>
          <meta charSet='utf-8' />
          <title>PixaBayFinder</title>
          <meta httpEquiv='X-UA-Compatible' content='IE=7' />
          <meta httpEquiv='X-UA-Compatible' content='ie=edge' />
          <meta httpEquiv='cache-control' content='no-cache' />
          <meta httpEquiv='expires' content='0' />
          <meta httpEquiv='pragma' content='no-cache' />
          <meta name='author' content='Fadi Hanna' />
          <meta name='keywords' content='API, Search, Pixabay, Finder' />
          <meta
            name='description'
            content='Pixabay Finder search photos from Pixabay API.'
          />
          <link
            type='image/'
            href='assets/pixabay-icon-filled.png?v=1'
            rel='icon'
          />
          <link
            href='assets/pixabay-icon-filled.png?v=1'
            rel='apple-touch-icon'
          />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <meta name='theme-color' content='#000000' />
          <meta name='description' content='PixaBayFinder' />
          <link href='manifest.json?v=1' rel='manifest' />
        </Head>
        <GlobalStyles />

        <body className={inter.className}>
          {children}
          <ToastContainer theme='dark' transition={Flip} />
        </body>
      </Provider>
    </html>
  );
}
