name: Create envfile

on: [push]

jobs:

  create-envfile:

    runs-on: ubuntu-23.10

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        REACT_APP_PUBLIC_PIXABAY_BASE_URL: ${{ secrets.REACT_APP_PUBLIC_PIXABAY_BASE_URL }}
        REACT_APP_PUBLIC_PIXABAY_KEY: ${{ secrets.REACT_APP_PUBLIC_PIXABAY_KEY }}
        file_name: .env
