name: TESTS

on:
  push:
    branches:
      - master

env:
        KEY: ${{secrets.NEXT_PUBLIC_PIXABAY_BASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read a var
        shell: bash
        run: "echo $KEY"
